#!/bin/bash

echo "🔄 Updating Remote Ethereum Dashboard on crab.local"
echo "=================================================="

# Check if we have the fixed files
if [ ! -f "ethereum-dashboard-fixed.html" ]; then
    echo "❌ Error: ethereum-dashboard-fixed.html not found"
    echo "Please run the dashboard fix first"
    exit 1
fi

if [ ! -f "ethereum-dashboard-server.py" ]; then
    echo "❌ Error: ethereum-dashboard-server.py not found"
    echo "Please run the dashboard fix first"
    exit 1
fi

echo "✅ Found fixed dashboard files"

# Check current remote dashboard status
echo "🔍 Checking current remote dashboard..."
curl -s http://crab.local:3000/ | grep -q "setTimeRange(\"1h\")" && {
    echo "❌ Remote dashboard still has JavaScript errors"
    echo "🔧 Need to update the remote server"
} || {
    echo "✅ Remote dashboard appears to be fixed"
    echo "🎉 No action needed!"
    exit 0
}

echo ""
echo "📋 To fix the remote dashboard, you need to:"
echo ""
echo "1. SSH to the crab server:"
echo "   ssh vovkes@crab.local"
echo ""
echo "2. Navigate to the dashboard directory:"
echo "   cd /opt/defimon/  # or wherever the dashboard is located"
echo ""
echo "3. Stop the current dashboard server:"
echo "   pkill -f 'python.*3000'"
echo "   # or find the process and kill it"
echo ""
echo "4. Replace the dashboard files with the fixed versions:"
echo "   # Copy the fixed files from your local machine:"
echo "   scp ethereum-dashboard-fixed.html vovkes@crab.local:/opt/defimon/"
echo "   scp ethereum-dashboard-server.py vovkes@crab.local:/opt/defimon/"
echo ""
echo "5. Start the fixed dashboard server:"
echo "   cd /opt/defimon/"
echo "   python3 ethereum-dashboard-server.py"
echo ""
echo "6. Test the dashboard:"
echo "   curl http://crab.local:3000/api/health"
echo ""

echo "🚀 Alternative: Use the deployment script"
echo "=========================================="
echo ""
echo "You can also use the existing deployment script:"
echo ""
echo "1. Run the deployment script:"
echo "   ./scripts/deploy-crab-ethereum-simple.sh"
echo ""
echo "2. This will set up the entire Ethereum node with the dashboard"
echo ""

echo "🔍 Quick verification commands:"
echo "==============================="
echo ""
echo "# Check if remote dashboard is fixed:"
echo "curl -s http://crab.local:3000/ | grep 'setTimeRange('"
echo ""
echo "# Should show: setTimeRange('1h') (with single quotes)"
echo "# Not: setTimeRange(\"1h\") (with double quotes)"
echo ""
echo "# Test API endpoints:"
echo "curl http://crab.local:3000/api/health"
echo "curl http://crab.local:3000/api/stats"
echo ""

echo "📝 Manual Update Steps (if needed):"
echo "===================================="
echo ""
echo "If you need to manually update the remote server:"
echo ""
echo "1. Find the dashboard server process:"
echo "   ssh vovkes@crab.local"
echo "   ps aux | grep python"
echo "   # Look for the process running on port 3000"
echo ""
echo "2. Stop the server:"
echo "   kill <PID>"
echo ""
echo "3. Find the dashboard files:"
echo "   find /opt/defimon -name '*.html' -o -name '*.py' | grep -i dashboard"
echo ""
echo "4. Replace the files:"
echo "   # Copy your fixed files to the server"
echo "   scp ethereum-dashboard-fixed.html vovkes@crab.local:/path/to/dashboard/"
echo ""
echo "5. Restart the server:"
echo "   cd /path/to/dashboard/"
echo "   python3 ethereum-dashboard-server.py &"
echo ""

echo "🎯 Expected Result:"
echo "=================="
echo ""
echo "After updating, the remote dashboard should:"
echo "✅ Have no JavaScript syntax errors"
echo "✅ Show working time period selection buttons"
echo "✅ Display charts properly"
echo "✅ Have functional API endpoints"
echo ""

echo "🔧 Troubleshooting:"
echo "=================="
echo ""
echo "If you still see errors:"
echo ""
echo "1. Check browser console for JavaScript errors"
echo "2. Verify the dashboard HTML was updated"
echo "3. Restart the dashboard server"
echo "4. Clear browser cache"
echo ""

echo "📞 Need Help?"
echo "============="
echo ""
echo "If you need assistance updating the remote server:"
echo "1. Check the deployment scripts in scripts/"
echo "2. Use the existing deployment infrastructure"
echo "3. The fixed dashboard files are ready to deploy"
echo ""
