services:
  geth:
    image: ethereum/client-go:stable
    container_name: geth-full-node
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
      - "6060:6060"
    volumes:
      - geth_data:/root/.ethereum
      - jwt_secret:/jwtsecret
      - ./start-geth.sh:/start-geth.sh:ro
    command: ["sh", "/start-geth.sh"]
    restart: unless-stopped
    profiles:
      - internal-geth

  lighthouse:
    image: sigp/lighthouse:latest
    container_name: lighthouse-beacon
    command: >-
      sh -lc '
        lighthouse bn \
          --network mainnet \
          --datadir /root/.lighthouse \
          --execution-endpoint $${EXECUTION_ENDPOINT:-http://geth:8551} \
          --execution-jwt /jwtsecret \
          $${CHECKPOINT_SYNC_URL:+--checkpoint-sync-url $${CHECKPOINT_SYNC_URL}} \
          --http \
          --http-address 0.0.0.0 \
          --http-port 5052 \
          --metrics \
          --metrics-address 0.0.0.0 \
          --metrics-port 5054
      '
    environment:
      - CHECKPOINT_SYNC_URL=${CHECKPOINT_SYNC_URL}
    # No hard depends_on to allow external execution client mode
    volumes:
      - ${LIGHTHOUSE_DATA_PATH:-lighthouse_data}:/root/.lighthouse
      - ${JWTSECRET_HEX_PATH:-./jwtsecret.hex}:/jwtsecret:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus-monitor
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9091:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana-dashboard
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  geth_data:
  prometheus_data:
  grafana_data:
  lighthouse_data:
  jwt_secret:
 
networks:
  default:
    name: geth-monitoring
