global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'geth'
    static_configs:
      - targets: ['geth:6060']
  - job_name: 'lighthouse'
    static_configs:
      - targets: ['lighthouse:5054']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
