runtime: nodejs20
service: default

env_variables:
  NODE_ENV: production

handlers:
  - url: /_next/static
    static_dir: .next/static
    secure: always
    http_headers:
      Cache-Control: "public, max-age=0, must-revalidate"

  - url: /static
    static_dir: public
    secure: always
    http_headers:
      Cache-Control: "public, max-age=0, must-revalidate"

  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
