global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'geth'
    static_configs:
      - targets: ['geth:6060']
    metrics_path: /debug/metrics/prometheus

  - job_name: 'lighthouse'
    static_configs:
      - targets: ['lighthouse:5052']
    metrics_path: /metrics
