apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    database: l2_analytics
    user: l2user
    secureJsonData:
      password: l2password
    jsonData:
      defaultDatabase: l2_analytics
      port: 8123
      server: clickhouse
      username: l2user
    editable: true
