apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: false
    editable: true
    jsonData:
      defaultDatabase: analytics
      port: 8123
      server: clickhouse
      username: default
      secure: false
      tlsSkipVerify: false
      timeout: 60
      queryTimeout: 60
      dialTimeout: 30
      maxExecutionTime: 60
      maxIdleConns: 100
      maxOpenConns: 100
      connMaxLifetime: 14400
    secureJsonData:
      password: password
