apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: defimon-postgres:5432
    database: defi_analytics
    user: postgres
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: password
