global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'analytics-api'
    static_configs:
      - targets: ['analytics-api:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'ai-ml-service'
    static_configs:
      - targets: ['ai-ml-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'data-ingestion'
    static_configs:
      - targets: ['data-ingestion:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'stream-processor'
    static_configs:
      - targets: ['stream-processor:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'kong'
    static_configs:
      - targets: ['api-gateway:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
