_format_version: "3.0"

services:
  - name: analytics-api
    url: http://analytics-api:8002
    routes:
      - name: analytics-routes
        paths:
          - /api/protocols
          - /api/analytics
          - /api/health
        strip_path: true
        methods:
          - GET
          - POST
          - OPTIONS
        protocols:
          - http
          - https

  - name: ai-ml-service
    url: http://ai-ml-service:8001
    routes:
      - name: ml-routes
        paths:
          - /api/ml
          - /api/predict
        strip_path: true
        methods:
          - GET
          - POST
          - OPTIONS
        protocols:
          - http
          - https

  - name: frontend
    url: http://frontend:3000
    routes:
      - name: frontend-routes
        paths:
          - /
        methods:
          - GET
          - POST
          - OPTIONS
        protocols:
          - http
          - https

  - name: admin-dashboard
    url: http://admin-dashboard:8080
    routes:
      - name: admin-routes
        paths:
          - /admin
          - /admin/
        strip_path: true
        methods:
          - GET
          - POST
          - OPTIONS
        protocols:
          - http
          - https

plugins:
  - name: rate-limiting
    config:
      minute: 100
      hour: 1000
      policy: local
      fault_tolerant: true
    service: analytics-api

  - name: rate-limiting
    config:
      minute: 50
      hour: 500
      policy: local
      fault_tolerant: true
    service: ai-ml-service

  - name: cors
    config:
      origins:
        - "http://localhost:3000"
        - "https://localhost:3000"
        - "http://frontend:3000"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
      exposed_headers:
        - X-Auth-Token
        - X-Request-ID
      credentials: true
      max_age: 3600
      preflight_continue: false

  - name: prometheus
    config:
      per_consumer: false
      per_service: true
      per_route: true
      status_codes: true
      bandwidth: true
      latency: true
      upstream_health: true

  - name: request-transformer
    config:
      add:
        headers:
          - X-Request-ID: ${uuid}
      remove:
        headers:
          - X-Request-ID

  - name: response-transformer
    config:
      add:
        headers:
          - X-Response-Time: ${response_time}
          - X-Service: ${service_name}

# API Authentication (Optional - for external API access)
# consumers:
#   - username: api_user
#     keyauth_credentials:
#       - key: your_api_key_here

# keyauth_credentials:
#   - consumer: api_user
#     key: your_api_key_here
