apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: defimon-frontend-cert
  namespace: defimon
spec:
  domains:
    - ${FRONTEND_DOMAIN}
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: defimon-admin-cert
  namespace: defimon
spec:
  domains:
    - ${ADMIN_DASHBOARD_DOMAIN}
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: defimon-api-cert
  namespace: defimon
spec:
  domains:
    - ${ANALYTICS_API_DOMAIN}
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: defimon-ai-cert
  namespace: defimon
spec:
  domains:
    - ${AI_ML_SERVICE_DOMAIN}
